import { User } from './user';
// Generated by https://quicktype.io

export interface Userabout {
  id: number;
  content: string;
  is_visible: string;
  created_at: string;
  updated_at: string;
  deleted_at: string;
  image_urls: string;
  userId: number;
  user: User;
}
